// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.

// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class feedback
    {
        private TopG_clothingEntities2 db = new TopG_clothingEntities2();

        public int feedback_id { get; set; }
        public int person_id { get; set; }
        public string feedback_desc { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }

        public virtual person person { get; set; }

        public string GetEmailByPersonId(int id)
        {
            var person = db.people.Find(id);

            if (person == null)
                return null;
            else
                return person.person_email;

        }
    }
}