//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<double> payment_amount_before { get; set; }
        public Nullable<double> payment_amount_after { get; set; }
        public string discount_code { get; set; }
        public Nullable<int> person_id { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual person person { get; set; }
    }
}
