//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Cart_item = new HashSet<Cart_item>();
            this.cartItems = new HashSet<cartItem>();
            this.wishlists = new HashSet<wishlist>();
        }
    
        public int product_id { get; set; }
        public string product_brand_name { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_price { get; set; }
        public string product_desc { get; set; }
        public Nullable<int> product_qty { get; set; }
        public string product_type { get; set; }
        public string product_size { get; set; }
        public Nullable<int> product_rating { get; set; }
        public string product_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_item> Cart_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cartItem> cartItems { get; set; }
        public virtual productSold productSold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlists { get; set; }
    }
}
