//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public int store_id { get; set; }
        public string store_name { get; set; }
        public string store_image { get; set; }
        public string store_open_times { get; set; }
        public string store_close_times { get; set; }
        public string store_address { get; set; }
        public string store_Phonenumber { get; set; }
    }
}
