//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucherCustomer
    {
        public int voucher_id { get; set; }
        public int person_id { get; set; }
        public Nullable<int> voucher_usage { get; set; }
    
        public virtual person person { get; set; }
        public virtual voucher voucher { get; set; }
    }
}
